# Generated by Django 4.1.7 on 2023-05-21 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('photo_dir', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_avatar',
            },
        ),
        migrations.CreateModel(
            name='TbInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_institucion_admin',
            },
        ),
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('username_canonical', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('email_canonical', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('salt', models.CharField(max_length=255)),
                ('locked', models.BooleanField(blank=True, null=True)),
                ('expired', models.BooleanField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('credentials_expired', models.BooleanField(blank=True, null=True)),
                ('credentials_expire_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('avatar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbavatar')),
                ('groups', models.ManyToManyField(blank=True, related_name='tb_user_roles', to='auth.group')),
                ('id_institucion', models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbinstitucion')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='tb_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'tb_user',
            },
        ),
    ]
