# Generated by Django 4.1.7 on 2023-05-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('photo_dir', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_avatar',
            },
        ),
        migrations.CreateModel(
            name='TbCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_category_admin',
            },
        ),
        migrations.CreateModel(
            name='TbCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_company',
            },
        ),
        migrations.CreateModel(
            name='TbCompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_company_type',
            },
        ),
        migrations.CreateModel(
            name='TbFunctionalGrouping',
            fields=[
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('functional_grouping_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('register_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_functional_grouping',
            },
        ),
        migrations.CreateModel(
            name='TbGroupRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('roles', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_group_roles',
            },
        ),
        migrations.CreateModel(
            name='TbResponsability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_responsability',
            },
        ),
        migrations.CreateModel(
            name='TbRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('roles', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_role',
            },
        ),
        migrations.CreateModel(
            name='TbStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('branch', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbcategory')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbcompany')),
                ('estructura_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbstructure')),
            ],
            options={
                'db_table': 'tb_structure_admin',
            },
        ),
        migrations.CreateModel(
            name='TbSystem',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('system_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('acronym', models.TextField(blank=True, null=True, unique=True)),
                ('routing', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_system',
            },
        ),
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('username_canonical', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('email_canonical', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField()),
                ('salt', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField()),
                ('expired', models.BooleanField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_requested_at', models.DateTimeField(blank=True, null=True)),
                ('roles', models.TextField()),
                ('credentials_expired', models.BooleanField()),
                ('credentials_expire_at', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbavatar')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbdpersona')),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='TbStructureResponsability',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('responsability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbresponsability')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbstructure')),
            ],
            options={
                'db_table': 'tb_structure_responsability',
            },
        ),
        migrations.CreateModel(
            name='TbrStructureContact',
            fields=[
                ('structure_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_item_id', models.IntegerField(blank=True, null=True)),
                ('structure_contact_value', models.CharField(max_length=50)),
                ('structure_contact_description', models.CharField(blank=True, max_length=1, null=True)),
                ('structure_contact_register_date', models.DateTimeField(blank=True, null=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbstructure')),
            ],
            options={
                'db_table': 'tbr_structure_contact',
            },
        ),
        migrations.CreateModel(
            name='TbRgrupoRolIp',
            fields=[
                ('id_grupo_rol_ip', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_grupo_rol', models.ForeignKey(blank=True, db_column='id_grupo_rol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbgrouproles')),
            ],
            options={
                'db_table': 'tb_rgrupo_rol_ip',
            },
        ),
        migrations.CreateModel(
            name='TbModule',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('module_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('acronym', models.TextField(blank=True, null=True)),
                ('system_code', models.ForeignKey(blank=True, db_column='system_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbsystem')),
            ],
            options={
                'db_table': 'tb_module',
            },
        ),
        migrations.CreateModel(
            name='TbFunctionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, max_length=6, null=True)),
                ('security_basic_role', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence_code', models.CharField(blank=True, max_length=3, null=True)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('functional_grouping_code', models.ForeignKey(blank=True, db_column='functional_grouping_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbfunctionalgrouping')),
                ('module_code', models.ForeignKey(blank=True, db_column='module_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbmodule')),
            ],
            options={
                'db_table': 'tb_functionality',
            },
        ),
        migrations.CreateModel(
            name='TbFunctionalGroupingModule',
            fields=[
                ('functional_grouping_module_id', models.AutoField(primary_key=True, serialize=False)),
                ('functional_grouping_code', models.ForeignKey(blank=True, db_column='functional_grouping_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbfunctionalgrouping')),
                ('module_code', models.ForeignKey(blank=True, db_column='module_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbmodule')),
            ],
            options={
                'db_table': 'tb_functional_grouping_module',
            },
        ),
        migrations.AddField(
            model_name='tbcompany',
            name='company_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbcompanytype'),
        ),
        migrations.CreateModel(
            name='TbUserGroupRoles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='adminschema.tbuser')),
                ('group_roles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbgrouproles')),
            ],
            options={
                'db_table': 'tb_user_group_roles',
                'unique_together': {('user', 'group_roles')},
            },
        ),
        migrations.CreateModel(
            name='TbRolGroupRoles',
            fields=[
                ('group_roles', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='adminschema.tbgrouproles')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbrole')),
            ],
            options={
                'db_table': 'tb_rol_group_roles',
                'unique_together': {('group_roles', 'rol')},
            },
        ),
    ]
