# Generated by Django 4.1.3 on 2023-09-26 03:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminschema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbinstitucion',
            name='db_name',
        ),
        migrations.AlterField(
            model_name='tbinstitucion',
            name='active_modules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('abastecimiento', 'Abastecimiento'), ('cajero', 'Cajero'), ('distribucion', 'Distribucion'), ('reservacion', 'Reservacion'), ('facturacion', 'Facturacion'), ('configuracion', 'Configuracion')], max_length=200), blank=True, default=list, size=None),
        ),
    ]
