# Generated by Django 4.1.7 on 2023-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminschema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbSystem',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('system_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('acronym', models.TextField(blank=True, null=True, unique=True)),
                ('routing', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_system',
            },
        ),
    ]
