# Generated by Django 4.1.3 on 2023-05-30 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('adminschema', '0002_tbsystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbuser',
            name='confirmation_token',
        ),
        migrations.RemoveField(
            model_name='tbuser',
            name='credentials_expire_at',
        ),
        migrations.RemoveField(
            model_name='tbuser',
            name='credentials_expired',
        ),
        migrations.RemoveField(
            model_name='tbuser',
            name='email_canonical',
        ),
        migrations.RemoveField(
            model_name='tbuser',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='tbuser',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='tbuser',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='tbuser',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='tbuser',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='tbuser',
            name='username_canonical',
        ),
        migrations.AddField(
            model_name='tbuser',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_rol', to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbuser',
            name='email',
            field=models.EmailField(default=3, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='tbuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
