# Generated by Django 4.1.7 on 2023-05-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('adminschema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbDimportacion',
            fields=[
                ('id_importacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_importacion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dimportacion',
            },
        ),
        migrations.CreateModel(
            name='TbDimportaciones',
            fields=[
                ('id_importacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_importacion', models.TextField()),
                ('activo', models.BooleanField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_registro', models.DateField()),
                ('importe_desayuno', models.FloatField(blank=True, null=True)),
                ('importe_doble_desayuno', models.FloatField(blank=True, null=True)),
                ('importe_almuerzo', models.FloatField(blank=True, null=True)),
                ('importe_doble_almuerzo', models.FloatField(blank=True, null=True)),
                ('importe_comida', models.FloatField(blank=True, null=True)),
                ('importe_doble_comida', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dimportaciones',
            },
        ),
        migrations.CreateModel(
            name='TbDimportacionRegistro',
            fields=[
                ('id_importacion_registro', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.CharField(max_length=255)),
                ('importe_reservaciones', models.FloatField(blank=True, null=True)),
                ('id_familiar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dimportacion_registro',
            },
        ),
        migrations.CreateModel(
            name='TbDpersonaRegla',
            fields=[
                ('id_persona_regla', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField()),
                ('reglas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dpersona_regla',
            },
        ),
        migrations.CreateModel(
            name='TbDreglaCobro',
            fields=[
                ('id_regla_cobro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_regla_cobro', models.TextField()),
                ('activo', models.BooleanField()),
                ('fijo', models.BooleanField()),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('eventos_afectados', models.TextField(blank=True, null=True)),
                ('dias_afectados', models.TextField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'tb_dregla_cobro',
            },
        ),
        migrations.CreateModel(
            name='TbNestadoImportacion',
            fields=[
                ('id_estado_importacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_importacion', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_nestado_importacion',
            },
        ),
        migrations.CreateModel(
            name='TbNtipoCobro',
            fields=[
                ('id_tipo_cobro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_cobro', models.TextField()),
                ('fecha_registro', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ntipo_cobro',
            },
        ),
        migrations.CreateModel(
            name='TbRfechaExcluida',
            fields=[
                ('id_fecha_excluida', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_rfecha_excluida',
            },
        ),
        migrations.CreateModel(
            name='TbTipoRegla',
            fields=[
                ('id_tipo_regla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_regla', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_tipo_regla',
            },
        ),
        migrations.CreateModel(
            name='TbRpersonaExcluidaCobro',
            fields=[
                ('id_persona_excluida_cobro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_importacion', models.ForeignKey(blank=True, db_column='id_importacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.tbdimportacion')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbdpersona')),
                ('id_usuario_registro', models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_registro_personaExcluidaCobro', to='adminschema.tbuser')),
            ],
            options={
                'db_table': 'tb_rpersona_excluida_cobro',
            },
        ),
        migrations.CreateModel(
            name='TbRimportacionReservacion',
            fields=[
                ('id_importacion_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_importacion', models.ForeignKey(blank=True, db_column='id_importacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.tbdimportacion')),
            ],
            options={
                'db_table': 'tb_rimportacion_reservacion',
            },
        ),
    ]
