# Generated by Django 4.1.7 on 2023-05-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajero', '0001_initial'),
        ('adminschema', '0001_initial'),
        ('base', '0001_initial'),
        ('reservacion', '0001_initial'),
        ('cobro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbrimportacionreservacion',
            name='id_reservacion',
            field=models.ForeignKey(blank=True, db_column='id_reservacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservacion.tbdreservacion'),
        ),
        migrations.AddField(
            model_name='tbrfechaexcluida',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoria'),
        ),
        migrations.AddField(
            model_name='tbrfechaexcluida',
            name='id_categoria_residente',
            field=models.ForeignKey(blank=True, db_column='id_categoria_residente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriaresidente'),
        ),
        migrations.AddField(
            model_name='tbrfechaexcluida',
            name='id_evento',
            field=models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento'),
        ),
        migrations.AddField(
            model_name='tbdreglacobro',
            name='id_tipo_regla',
            field=models.ForeignKey(blank=True, db_column='id_tipo_regla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.tbtiporegla'),
        ),
        migrations.AddField(
            model_name='tbdreglacobro',
            name='id_usuario_registro',
            field=models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_registro_reglaCobro', to='adminschema.tbuser'),
        ),
        migrations.AddField(
            model_name='tbdpersonaregla',
            name='id_persona',
            field=models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbdpersona'),
        ),
        migrations.AddField(
            model_name='tbdimportacionregistro',
            name='id_importacion',
            field=models.ForeignKey(db_column='id_importacion', on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.tbdimportaciones'),
        ),
        migrations.AddField(
            model_name='tbdimportaciones',
            name='id_usuario_registro',
            field=models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_registro_importaciones', to='adminschema.tbuser'),
        ),
        migrations.AddField(
            model_name='tbdimportacion',
            name='id_estado_importacion',
            field=models.ForeignKey(blank=True, db_column='id_estado_importacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.tbnestadoimportacion'),
        ),
        migrations.AddField(
            model_name='tbdimportacion',
            name='id_usuario_modificacion',
            field=models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_modificacion_importacion', to='adminschema.tbuser'),
        ),
        migrations.AddField(
            model_name='tbdimportacion',
            name='id_usuario_registro',
            field=models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_registro_importacion', to='adminschema.tbuser'),
        ),
    ]
