# Generated by Django 4.2.5 on 2023-10-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_tbntipoestructura_fecha_registro_tipo_estructura'),
        ('autenticacion', '0002_initial'),
        ('cajero', '0004_alter_tbrpersonatarjeta_id_persona'),
        ('cobro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbNconfiguracionCobro',
            fields=[
                ('id_configuracion_cobro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_configuracion_cobro', models.TextField()),
                ('fecha_registro', models.DateField(auto_now=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.institucion')),
            ],
            options={
                'db_table': 'tb_nconfiguracion_cobro',
            },
        ),
        migrations.CreateModel(
            name='TbNvaloresConfiguracionCobro',
            fields=[
                ('id_valores_configuracion_cobro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoria')),
                ('id_categoria_residente', models.ForeignKey(blank=True, db_column='id_categoria_residente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriaresidente')),
                ('id_configuracion_cobro', models.ForeignKey(blank=True, db_column='id_configuracion_cobro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.tbnconfiguracioncobro')),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.institucion')),
            ],
            options={
                'db_table': 'tb_nvalores_configuracion_cobro',
            },
        ),
        migrations.RemoveField(
            model_name='tbdimportaciones',
            name='id_usuario_registro',
        ),
        migrations.RemoveField(
            model_name='tbdimportacionregistro',
            name='id_importacion',
        ),
        migrations.RemoveField(
            model_name='tbdpersonaregla',
            name='id_persona',
        ),
        migrations.RemoveField(
            model_name='tbdreglacobro',
            name='id_tipo_regla',
        ),
        migrations.RemoveField(
            model_name='tbdreglacobro',
            name='id_usuario_registro',
        ),
        migrations.RemoveField(
            model_name='tbrfechaexcluida',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='tbrfechaexcluida',
            name='id_categoria_residente',
        ),
        migrations.RemoveField(
            model_name='tbrfechaexcluida',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='tbrimportacionreservacion',
            name='id_importacion',
        ),
        migrations.RemoveField(
            model_name='tbrpersonaexcluidacobro',
            name='id_importacion',
        ),
        migrations.RemoveField(
            model_name='tbrpersonaexcluidacobro',
            name='id_persona',
        ),
        migrations.RemoveField(
            model_name='tbrpersonaexcluidacobro',
            name='id_usuario_registro',
        ),
        migrations.AddField(
            model_name='tbntipocobro',
            name='id_institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.institucion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TbDimportacion',
        ),
        migrations.DeleteModel(
            name='TbDimportaciones',
        ),
        migrations.DeleteModel(
            name='TbDimportacionRegistro',
        ),
        migrations.DeleteModel(
            name='TbDpersonaRegla',
        ),
        migrations.DeleteModel(
            name='TbDreglaCobro',
        ),
        migrations.DeleteModel(
            name='TbNestadoImportacion',
        ),
        migrations.DeleteModel(
            name='TbRfechaExcluida',
        ),
        migrations.DeleteModel(
            name='TbRimportacionReservacion',
        ),
        migrations.DeleteModel(
            name='TbRpersonaExcluidaCobro',
        ),
        migrations.DeleteModel(
            name='TbTipoRegla',
        ),
        migrations.AddField(
            model_name='tbnvaloresconfiguracioncobro',
            name='id_tipo_cobro',
            field=models.ForeignKey(blank=True, db_column='id_tipo_cobro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.tbntipocobro'),
        ),
    ]
