# Generated by Django 4.1.3 on 2023-09-21 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminschema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.TextField()),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='TbDdistribucion',
            fields=[
                ('id_distribucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('fecha_distribucion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('es_principal', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ddistribucion',
            },
        ),
        migrations.CreateModel(
            name='TbDtarjetaAlimentacion',
            fields=[
                ('id_tarjeta_alimentacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, default='12345COD', null=True)),
                ('numero_serie', models.TextField(blank=True, default='12345NO', null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dtarjeta_alimentacion',
            },
        ),
        migrations.CreateModel(
            name='TbNclasificacionEvento',
            fields=[
                ('id_clasificacion_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clasificacion_evento', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_clasificacion_evento', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_nclasificacion_evento',
            },
        ),
        migrations.CreateModel(
            name='TbNdiaSemana',
            fields=[
                ('id_dia_semana', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tb_ndia_semana',
            },
        ),
        migrations.CreateModel(
            name='TbNevento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('descripcion_evento', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('accesos', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('icono', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('evento_padre', models.ForeignKey(blank=True, db_column='evento_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento')),
                ('id_clasificacion_evento', models.ForeignKey(blank=True, db_column='id_clasificacion_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnclasificacionevento')),
            ],
            options={
                'db_table': 'tb_nevento',
            },
        ),
        migrations.CreateModel(
            name='TbNhorario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_horario', models.TextField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField()),
                ('dias_semana', models.ManyToManyField(to='cajero.tbndiasemana')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_nhorario',
            },
        ),
        migrations.CreateModel(
            name='TbNrangoEvento',
            fields=[
                ('id_rango_evento', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_rango_evento', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_nrango_evento',
            },
        ),
        migrations.CreateModel(
            name='TbNregla',
            fields=[
                ('id_regla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_regla', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_regla', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_nregla',
            },
        ),
        migrations.CreateModel(
            name='TbStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('initials', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('centro_costo', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbcategory')),
                ('estructura_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cajero.tbstructure')),
                ('id_especialista_complejo', models.ForeignKey(blank=True, db_column='id_especialista_complejo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_especialista_complejo_Structure', to='base.tbdpersona')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_sub_director', models.ForeignKey(blank=True, db_column='id_sub_director', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_sub_director_Structure', to='base.tbdpersona')),
                ('id_tecnico_general', models.ForeignKey(blank=True, db_column='id_tecnico_general', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_tecnico_general_Structure', to='base.tbdpersona')),
            ],
            options={
                'db_table': 'tb_structure',
            },
        ),
        migrations.CreateModel(
            name='TbRpersonaTarjeta',
            fields=[
                ('id_persona_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbdpersona')),
                ('id_tarjeta', models.ForeignKey(blank=True, db_column='id_tarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbdtarjetaalimentacion')),
            ],
            options={
                'db_table': 'tb_rpersona_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='TbReventoRangoEvento',
            fields=[
                ('id_evento_rango_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_rango_evento', models.ForeignKey(blank=True, db_column='id_rango_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnrangoevento')),
                ('id_usuario_registro', models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_revento_rango_evento',
            },
        ),
        migrations.CreateModel(
            name='TbReventoHorario',
            fields=[
                ('id_evento_horario', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento')),
                ('id_horario', models.ForeignKey(db_column='id_horario', on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnhorario')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_revento_horario',
            },
        ),
        migrations.CreateModel(
            name='TbRestructuraRegla',
            fields=[
                ('id_estructura_regla', models.AutoField(primary_key=True, serialize=False)),
                ('id_valor_regla', models.IntegerField(blank=True, null=True)),
                ('nombre_valor_regla', models.TextField(blank=True, null=True)),
                ('id_estructura', models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbstructure')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_regla', models.ForeignKey(blank=True, db_column='id_regla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnregla')),
            ],
            options={
                'db_table': 'tb_restructura_regla',
            },
        ),
        migrations.CreateModel(
            name='TbRdistribucionRegla',
            fields=[
                ('id_distribucion_regla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_regla', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('nombre_valor_regla', models.TextField(blank=True, null=True)),
                ('id_distribucion', models.ForeignKey(blank=True, db_column='id_distribucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbddistribucion')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_rdistribucion_regla',
            },
        ),
        migrations.CreateModel(
            name='TbNunidadMedida',
            fields=[
                ('id_unidad_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unidad_medida', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_unidad_medida', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('siglas', models.TextField(blank=True, null=True)),
                ('clasificacion', models.TextField()),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_nunidad_medida',
            },
        ),
        migrations.CreateModel(
            name='TbNtipoTarjeta',
            fields=[
                ('id_tipo_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_tarjeta', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_ntipo_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='TbNtipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_producto', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_tipo_producto', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_ntipo_producto',
            },
        ),
        migrations.AddField(
            model_name='tbnevento',
            name='id_horario',
            field=models.ForeignKey(blank=True, db_column='id_horario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnhorario'),
        ),
        migrations.AddField(
            model_name='tbnevento',
            name='id_institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion'),
        ),
        migrations.CreateModel(
            name='TbNestadoTarjeta',
            fields=[
                ('id_estado_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_tarjeta', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_nestado_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='TbNestadoMovimientoAsignacion',
            fields=[
                ('id_estado_movimiento_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_movimiento_asignacion', models.TextField()),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_nestado_movimiento_asignacion',
            },
        ),
        migrations.CreateModel(
            name='TbNclasificacionPlato',
            fields=[
                ('id_clasificacion_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clasificacion_plato', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_clasificacion_plato', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_nclasificacion_plato',
            },
        ),
        migrations.CreateModel(
            name='TbNclasificacionDistribucion',
            fields=[
                ('id_clasificacion_distribucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_nclasificacion_distribucion',
            },
        ),
        migrations.CreateModel(
            name='TbMovimientoAsignacion',
            fields=[
                ('id_movimiento_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('hora_movimiento_registro', models.TimeField(blank=True, null=True)),
                ('hora_movimiento_modificacion', models.TimeField(blank=True, null=True)),
                ('id_estado_movimiento_asignacion', models.ForeignKey(blank=True, db_column='id_estado_movimiento_asignacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnestadomovimientoasignacion')),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_puerta_destino', models.ForeignKey(blank=True, db_column='id_puerta_destino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_puerta_destino_MovimientoAsignacion', to='cajero.tbstructure')),
                ('id_puerta_origen', models.ForeignKey(blank=True, db_column='id_puerta_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_puerta_origen_MovimientoAsignacion', to='cajero.tbstructure')),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_modificacion_MovimientoAsignacion', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_registro', models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_registro_MovimientoAsignacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_movimiento_asignacion',
            },
        ),
        migrations.CreateModel(
            name='TbLastDistribucion',
            fields=[
                ('id_temp', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.CharField(blank=True, max_length=255, null=True)),
                ('id_usuario_registro', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('id_usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('id_distribucion', models.IntegerField(blank=True, null=True)),
                ('id_complejo_comedor', models.IntegerField(blank=True, null=True)),
                ('id_comedor', models.IntegerField(blank=True, null=True)),
                ('id_puerta', models.IntegerField(blank=True, null=True)),
                ('id_evento', models.IntegerField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_last_distribucion',
            },
        ),
        migrations.CreateModel(
            name='TbDvaloresRegla',
            fields=[
                ('id_valores_regla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_valores_regla', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_valor_regla', models.IntegerField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_regla', models.ForeignKey(blank=True, db_column='id_regla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnregla')),
            ],
            options={
                'db_table': 'tb_dvalores_regla',
            },
        ),
        migrations.CreateModel(
            name='TbDtarjetaDistribucion',
            fields=[
                ('id_tarjeta_distribucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_comedor', models.ForeignKey(blank=True, db_column='id_comedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_comedor_tarjeta', to='cajero.tbstructure')),
                ('id_complejo_comedor', models.ForeignKey(blank=True, db_column='id_complejo_comedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_complejo_comedor_tarjeta', to='cajero.tbstructure')),
                ('id_distribucion', models.ForeignKey(blank=True, db_column='id_distribucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_distribucion_tarjeta', to='cajero.tbddistribucion')),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_evento_tarjeta', to='cajero.tbnevento')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_puerta', models.ForeignKey(blank=True, db_column='id_puerta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_puerta_tarjeta', to='cajero.tbstructure')),
                ('id_tarjeta', models.ForeignKey(blank=True, db_column='id_tarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbdtarjetaalimentacion')),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_modificacion_distribucion', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_registro', models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dtarjeta_distribucion',
            },
        ),
        migrations.AddField(
            model_name='tbdtarjetaalimentacion',
            name='id_estado_tarjeta',
            field=models.ForeignKey(blank=True, db_column='id_estado_tarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnestadotarjeta'),
        ),
        migrations.AddField(
            model_name='tbdtarjetaalimentacion',
            name='id_institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion'),
        ),
        migrations.AddField(
            model_name='tbdtarjetaalimentacion',
            name='id_tipo_tarjeta',
            field=models.ForeignKey(blank=True, db_column='id_tipo_tarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbntipotarjeta'),
        ),
        migrations.AddField(
            model_name='tbdtarjetaalimentacion',
            name='id_usuario_modificacion',
            field=models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_modificacion_tarjetaAlimentacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tbdtarjetaalimentacion',
            name='id_usuario_registro',
            field=models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_registro_tarjetaAlimentacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TbDsolapinPerdido',
            fields=[
                ('id_solapin_perdido', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_solapin', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_persona_solapin_perdido', to='base.tbdpersona')),
                ('id_usuario_registro', models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dsolapin_perdido',
            },
        ),
        migrations.CreateModel(
            name='TbDproducto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_cup', models.FloatField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_tipo_producto', models.ForeignKey(db_column='id_tipo_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbntipoproducto')),
                ('id_unidad_medida', models.ForeignKey(blank=True, db_column='id_unidad_medida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_unidad_medida_producto', to='cajero.tbnunidadmedida')),
            ],
            options={
                'db_table': 'tb_dproducto',
            },
        ),
        migrations.CreateModel(
            name='TbDpersonaIPPuerta',
            fields=[
                ('id_persona_puerta', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('ip_puerta', models.TextField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbdpersona')),
                ('id_puerta', models.ForeignKey(blank=True, db_column='id_puerta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbstructure')),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_modificacion_personaPuerta', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_registro', models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_registro_personaPuerta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dpersona_puerta',
            },
        ),
        migrations.CreateModel(
            name='TbDpersonaDistribucion',
            fields=[
                ('id_persona_distribucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('id_comedor', models.ForeignKey(blank=True, db_column='id_comedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_comedor_persona', to='cajero.tbstructure')),
                ('id_complejo_comedor', models.ForeignKey(blank=True, db_column='id_complejo_comedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_complejo_comedor_distribucionpersona', to='cajero.tbstructure')),
                ('id_distribucion', models.ForeignKey(blank=True, db_column='id_distribucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_distribucion_persona', to='cajero.tbddistribucion')),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_evento_persona', to='cajero.tbnevento')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_persona_dist', to='base.tbdpersona')),
                ('id_puerta', models.ForeignKey(blank=True, db_column='id_puerta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_puerta_persona', to='cajero.tbstructure')),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_usuario_modificacion_distribucionpersona', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_registro', models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dpersona_distribucion',
            },
        ),
        migrations.AddField(
            model_name='tbddistribucion',
            name='id_clasificacion_distribucion',
            field=models.ForeignKey(blank=True, db_column='id_clasificacion_distribucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnclasificaciondistribucion'),
        ),
        migrations.AddField(
            model_name='tbddistribucion',
            name='id_evento',
            field=models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento'),
        ),
        migrations.AddField(
            model_name='tbddistribucion',
            name='id_institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion'),
        ),
        migrations.AddField(
            model_name='tbddistribucion',
            name='id_usuario_registro',
            field=models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TbDconfiguracionTarjeta',
            fields=[
                ('id_configuracion_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_comedor', models.ForeignKey(blank=True, db_column='id_comedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_comedor_configuracionTarjeta', to='cajero.tbstructure')),
                ('id_complejo_comedor', models.ForeignKey(blank=True, db_column='id_complejo_comedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_complejo_comedor_configuracionTarjeta', to='cajero.tbstructure')),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
                ('id_puerta', models.ForeignKey(blank=True, db_column='id_puerta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_puerta_configuracionTarjeta', to='cajero.tbstructure')),
                ('id_tarjeta_alimentacion', models.ForeignKey(blank=True, db_column='id_tarjeta_alimentacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbdtarjetaalimentacion')),
            ],
            options={
                'db_table': 'tb_dconfiguracion_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='TbDconfiguracionProducto',
            fields=[
                ('id_configuracion_producto', models.AutoField(primary_key=True, serialize=False)),
                ('gramaje', models.FloatField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('valor_merma', models.FloatField(blank=True, null=True)),
                ('cantidad_disponible', models.FloatField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('entidad_actualiza', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_producto_config', to='cajero.tbdproducto')),
                ('id_usuario_registro', models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dconfiguracion_producto',
            },
        ),
        migrations.CreateModel(
            name='TbDaccesoEventoSecundario',
            fields=[
                ('id_acceso_evento_secundario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_acceso', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminschema.tbinstitucion')),
            ],
            options={
                'db_table': 'tb_dacceso_evento_secundario',
            },
        ),
    ]
