# Generated by Django 4.2.5 on 2023-10-11 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
        ('cajero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdsolapinperdido',
            name='id_persona',
            field=models.OneToOneField(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_persona_solapin_perdido', to='autenticacion.persona'),
        ),
    ]
