# Generated by Django 4.1.3 on 2023-06-08 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminschema', '0003_remove_tbuser_confirmation_token_and_more'),
        ('cajero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbdalmacen',
            name='id_institucion',
            field=models.ForeignKey(db_column=' id_institucion', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbinstitucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbnclasificacionproducto',
            name='id_institucion',
            field=models.ForeignKey(db_column=' id_institucion', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='adminschema.tbinstitucion'),
            preserve_default=False,
        ),
    ]
