# Generated by Django 4.1.3 on 2023-07-16 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbdproducto',
            name='id_asset',
        ),
        migrations.RemoveField(
            model_name='tbdproducto',
            name='precio_cuc',
        ),
    ]
