# Generated by Django 4.2.5 on 2023-10-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0002_alter_tbrpersonatarjeta_id_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbrpersonatarjeta',
            name='id_tarjeta',
            field=models.ForeignKey(blank=True, db_column='id_tarjeta', null=True, on_delete=django.db.models.deletion.CASCADE, to='cajero.tbdtarjetaalimentacion'),
        ),
    ]
