# Generated by Django 4.1.3 on 2023-08-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0002_remove_tbdproducto_id_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdtarjetaalimentacion',
            name='codigo',
            field=models.TextField(blank=True, default='12345COD', null=True),
        ),
        migrations.AlterField(
            model_name='tbdtarjetaalimentacion',
            name='numero_serie',
            field=models.TextField(blank=True, default='12345NO', null=True),
        ),
    ]
