# Generated by Django 4.1.3 on 2023-09-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0003_alter_tbdtarjetaalimentacion_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcategory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tbcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
