# Generated by Django 4.1.3 on 2023-09-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0004_alter_tbcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbstructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
