# Generated by Django 4.1.3 on 2023-09-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0006_alter_tbstructure_estructura_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbstructure',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
