# Generated by Django 4.1.7 on 2023-05-21 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
        ('cajero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbDavisos',
            fields=[
                ('id_aviso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_usuario_registro', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_davisos',
            },
        ),
        migrations.CreateModel(
            name='TbDconfiguracionCobro',
            fields=[
                ('id_configuracion_cobro', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dconfiguracion_cobro',
            },
        ),
        migrations.CreateModel(
            name='TbDconfiguracionEventoAcceso',
            fields=[
                ('id_configuracion_evento_acceso', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dconfiguracion_evento_acceso',
            },
        ),
        migrations.CreateModel(
            name='TbDconfiguracionPersona',
            fields=[
                ('id_configuracion_persona', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dconfiguracion_persona',
            },
        ),
        migrations.CreateModel(
            name='TbDvaloresConfiguracionPersona',
            fields=[
                ('id_calores_configuracion_persona', models.AutoField(primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoria')),
                ('id_categoria_residente', models.ForeignKey(blank=True, db_column='id_categoria_residente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriaresidente')),
                ('id_configuracion_persona', models.ForeignKey(blank=True, db_column='id_configuracion_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.tbdconfiguracionpersona')),
                ('id_estructura', models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnestructura')),
                ('id_tipo_curso', models.ForeignKey(blank=True, db_column='id_tipo_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbntipocurso')),
            ],
            options={
                'db_table': 'tb_dvalores_configuracion_persona',
            },
        ),
        migrations.CreateModel(
            name='TbDvaloresConfiguracionEventoAcceso',
            fields=[
                ('id_valores_configuracion_evento_acceso', models.AutoField(primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoria')),
                ('id_categoria_residente', models.ForeignKey(blank=True, db_column='id_categoria_residente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriaresidente')),
                ('id_configuracion_evento_acceso', models.ForeignKey(db_column='id_configuracion_evento_acceso', on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.tbdconfiguracioneventoacceso')),
                ('id_dia_semana', models.ForeignKey(blank=True, db_column='id_dia_semana', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbndiasemana')),
                ('id_estructura', models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnestructura')),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento')),
                ('id_tipo_curso', models.ForeignKey(blank=True, db_column='id_tipo_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbntipocurso')),
            ],
            options={
                'db_table': 'tb_dvalores_configuracion_evento_acceso',
            },
        ),
        migrations.CreateModel(
            name='TbDvaloresConfiguracionCobro',
            fields=[
                ('id_valores_configuracion_cobro', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_cobro', models.IntegerField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoria')),
                ('id_categoria_residente', models.ForeignKey(blank=True, db_column='id_categoria_residente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriaresidente')),
                ('id_configuracion_cobro', models.ForeignKey(blank=True, db_column='id_configuracion_cobro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.tbdconfiguracioncobro')),
                ('id_estructura', models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnestructura')),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento')),
                ('id_tipo_curso', models.ForeignKey(blank=True, db_column='id_tipo_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbntipocurso')),
            ],
            options={
                'db_table': 'tb_dvalores_configuracion_cobro',
            },
        ),
        migrations.CreateModel(
            name='TbDplanificacionMenu',
            fields=[
                ('id_planificacion_menu', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cantidad_reservaciones_desayuno', models.IntegerField(blank=True, null=True)),
                ('cantidad_por_configuracion_desayuno', models.IntegerField(blank=True, null=True)),
                ('planificacion_desayuno', models.IntegerField(blank=True, null=True)),
                ('cantidad_reservaciones_almuerzo', models.IntegerField(blank=True, null=True)),
                ('cantidad_por_configuracion_almuerzo', models.IntegerField(blank=True, null=True)),
                ('planificacion_almuerzo', models.IntegerField(blank=True, null=True)),
                ('cantidad_reservaciones_comida', models.IntegerField(blank=True, null=True)),
                ('cantidad_por_configuracion_comida', models.IntegerField(blank=True, null=True)),
                ('planificacion_comida', models.IntegerField(blank=True, null=True)),
                ('id_complejo', models.ForeignKey(db_column='id_complejo', on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbstructure')),
            ],
            options={
                'db_table': 'tb_dplanificacion_menu',
            },
        ),
        migrations.CreateModel(
            name='TbDdatosContacto',
            fields=[
                ('id_datos_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('correo', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_usuario_registro', models.ForeignKey(db_column='id_usuario_registro', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_ddatos_contacto',
            },
        ),
        migrations.CreateModel(
            name='TbDcron',
            fields=[
                ('id_cron', models.AutoField(primary_key=True, serialize=False)),
                ('scrip', models.TextField(blank=True, null=True)),
                ('frecuencia', models.IntegerField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('unidad_tiempo', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('proxima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_registro', models.ForeignKey(db_column='id_usuario_registro', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dcron',
            },
        ),
        migrations.CreateModel(
            name='TbDconfiguracionRabbitmq',
            fields=[
                ('id_configuracion_rabbitmq', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.TextField(blank=True, null=True)),
                ('puerto', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.TextField(blank=True, null=True)),
                ('contrasena', models.TextField(blank=True, null=True)),
                ('id_usuario_registro', models.ForeignKey(db_column='id_usuario_registro', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dconfiguracion_rabbitmq',
            },
        ),
        migrations.CreateModel(
            name='TbDconfiguracionProceso',
            fields=[
                ('id_configuracion_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('flujo', models.BooleanField(blank=True, null=True)),
                ('descripcion_configuracion_proceso', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_usuario_registro', models.ForeignKey(db_column='id_usuario_registro', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dconfiguracion_proceso',
            },
        ),
        migrations.CreateModel(
            name='TbDconfiguracionElastic',
            fields=[
                ('id_configuracion_elastic', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.TextField(blank=True, null=True)),
                ('puerto', models.TextField(blank=True, null=True)),
                ('config_indice', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_registro', models.ForeignKey(db_column='id_usuario_registro', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dconfiguracion_elastic',
            },
        ),
    ]
