# Generated by Django 4.1.3 on 2023-09-21 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbDelementosMostrar',
            fields=[
                ('id_elementos_mostrar', models.AutoField(primary_key=True, serialize=False)),
                ('elementos_mostrar_menu', models.IntegerField(blank=True, null=True)),
                ('elementos_mostrar_reservacion', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('elementos_mostrar_calendario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_delementos_mostrar',
            },
        ),
        migrations.CreateModel(
            name='TbDperiodoReservacion',
            fields=[
                ('id_periodo_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_reservacion', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dperiodo_reservacion',
            },
        ),
        migrations.CreateModel(
            name='TbHistorialReservacion',
            fields=[
                ('id_historial_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.CharField(max_length=1)),
                ('usuario_platos', models.JSONField(blank=True, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('fecha_reservacion', models.DateField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateField(blank=True, null=True)),
                ('por_plato', models.BooleanField(blank=True, null=True)),
                ('id_configuracion_cobro', models.IntegerField(blank=True, null=True)),
                ('id_menu', models.IntegerField()),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('cobrada', models.BooleanField(blank=True, null=True)),
                ('id_evento', models.IntegerField()),
                ('id_reservacion', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_historial_reservacion',
            },
        ),
        migrations.CreateModel(
            name='TbDresponsableReservacion',
            fields=[
                ('id_responsable_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_estructura', models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnestructura')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_persona_responsable', to='base.tbdpersona')),
                ('id_persona_registro', models.ForeignKey(blank=True, db_column='id_persona_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dresponsable_reservacion',
            },
        ),
        migrations.CreateModel(
            name='TbDresponsableAreaPersonas',
            fields=[
                ('id_responsable_area_personas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_estructura', models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnestructura')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_persona_resp_area', to='base.tbdpersona')),
                ('id_persona_registro', models.ForeignKey(blank=True, db_column='id_persona_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dresponsable_area_personas',
            },
        ),
    ]
