# Generated by Django 4.1.7 on 2023-05-21 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
        ('cajero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbDelementosMostrar',
            fields=[
                ('id_elementos_mostrar', models.AutoField(primary_key=True, serialize=False)),
                ('elementos_mostrar_menu', models.IntegerField(blank=True, null=True)),
                ('elementos_mostrar_reservacion', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('elementos_mostrar_calendario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_delementos_mostrar',
            },
        ),
        migrations.CreateModel(
            name='TbDperiodoReservacion',
            fields=[
                ('id_periodo_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_reservacion', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dperiodo_reservacion',
            },
        ),
        migrations.CreateModel(
            name='TbDreservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reservacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_cancelacion', models.DateField(blank=True, null=True)),
                ('costo_reservacion', models.FloatField(blank=True, null=True)),
                ('es_por_plato', models.BooleanField(blank=True, null=True)),
                ('id_menu', models.IntegerField(blank=True, null=True)),
                ('token_reservacion', models.TextField(blank=True, null=True)),
                ('cobrada', models.BooleanField(blank=True, null=True)),
                ('guardado', models.BooleanField(blank=True, null=True)),
                ('id_configuracion_cobro', models.ForeignKey(blank=True, db_column='id_configuracion_cobro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.tbdconfiguracioncobro')),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbdpersona')),
                ('id_persona_distribucion', models.ForeignKey(blank=True, db_column='id_persona_distribucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbdpersonadistribucion')),
            ],
            options={
                'db_table': 'tb_dreservacion',
            },
        ),
        migrations.CreateModel(
            name='TbHistorialReservacion',
            fields=[
                ('id_historial_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.CharField(max_length=1)),
                ('usuario_platos', models.JSONField(blank=True, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('fecha_reservacion', models.DateField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateField(blank=True, null=True)),
                ('por_plato', models.BooleanField(blank=True, null=True)),
                ('id_configuracion_cobro', models.IntegerField(blank=True, null=True)),
                ('id_menu', models.IntegerField()),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('cobrada', models.BooleanField(blank=True, null=True)),
                ('id_evento', models.IntegerField()),
                ('id_reservacion', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_historial_reservacion',
            },
        ),
        migrations.CreateModel(
            name='TbRticketReservacion',
            fields=[
                ('id_ticket_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('ticket', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_reservacion', models.ForeignKey(blank=True, db_column='id_reservacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservacion.tbdreservacion')),
                ('id_usuario_registro', models.ForeignKey(blank=True, db_column='id_persona_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_rticket_reservacion',
            },
        ),
        migrations.CreateModel(
            name='TbRreservacionPlato',
            fields=[
                ('id_reservacion_plato', models.AutoField(primary_key=True, serialize=False)),
                ('guardado', models.BooleanField(blank=True, null=True)),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnevento')),
                ('id_menu', models.ForeignKey(blank=True, db_column='id_menu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbdmenu')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbdpersona')),
                ('id_plato', models.ForeignKey(blank=True, db_column='id_plato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cajero.tbnplato')),
                ('id_reservacion', models.ForeignKey(blank=True, db_column='id_reservacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservacion.tbdreservacion')),
            ],
            options={
                'db_table': 'tb_rreservacion_plato',
            },
        ),
        migrations.CreateModel(
            name='TbDresponsableReservacion',
            fields=[
                ('id_responsable_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_estructura', models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnestructura')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbdpersona')),
                ('id_persona_registro', models.ForeignKey(blank=True, db_column='id_persona_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dresponsable_reservacion',
            },
        ),
        migrations.CreateModel(
            name='TbDresponsableAreaPersonas',
            fields=[
                ('id_responsable_area_personas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_estructura', models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnestructura')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbdpersona')),
                ('id_persona_registro', models.ForeignKey(blank=True, db_column='id_persona_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_dresponsable_area_personas',
            },
        ),
    ]
