# Generated by Django 4.2.5 on 2023-10-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_initial'),
        ('reservacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdresponsableareapersonas',
            name='id_persona',
            field=models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_persona_resp_area', to='autenticacion.persona'),
        ),
        migrations.AlterField(
            model_name='tbdresponsablereservacion',
            name='id_persona',
            field=models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_persona_responsable', to='autenticacion.persona'),
        ),
        migrations.DeleteModel(
            name='TbHistorialReservacion',
        ),
    ]
