# Generated by Django 4.1.3 on 2023-07-04 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminschema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbDpersona',
            fields=[
                ('tbuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_persona', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('ci', models.CharField(max_length=255)),
                ('solapin', models.CharField(blank=True, max_length=255, null=True)),
                ('id_expediente', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField()),
                ('id_persona_foto', models.CharField(blank=True, max_length=36, null=True)),
                ('nombre_responsabilidad', models.TextField(blank=True, null=True)),
                ('codigo_solapin', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tb_dpersona',
            },
            bases=('adminschema.tbuser',),
        ),
        migrations.CreateModel(
            name='TbNcarrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_carrera', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ncarrera',
            },
        ),
        migrations.CreateModel(
            name='TbNcategoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('fecha_registro_categoria', models.DateTimeField()),
                ('descripcion_categoria', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_ncategoria',
            },
        ),
        migrations.CreateModel(
            name='TbNcategoriaCientifica',
            fields=[
                ('id_categoria_cientifica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_cientifica', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ncategoria_cientifica',
            },
        ),
        migrations.CreateModel(
            name='TbNcategoriaDocente',
            fields=[
                ('id_categoria_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_docente', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ncategoria_docente',
            },
        ),
        migrations.CreateModel(
            name='TbNcategoriaResidente',
            fields=[
                ('id_categoria_residente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_residente', models.TextField()),
                ('fecha_registro', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('siglas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ncategoria_residente',
            },
        ),
        migrations.CreateModel(
            name='TbNedificio',
            fields=[
                ('id_edificio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_edificio', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_edificio', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_nedificio',
            },
        ),
        migrations.CreateModel(
            name='TbNgrupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ngrupo',
            },
        ),
        migrations.CreateModel(
            name='TbNorigen',
            fields=[
                ('id_origen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_origen', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_origen', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_norigen',
            },
        ),
        migrations.CreateModel(
            name='TbNpais',
            fields=[
                ('nombre_pais', models.CharField(max_length=255)),
                ('fecha_registro_pais', models.DateTimeField()),
                ('descripcion_pais', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('id_pais', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_npais',
            },
        ),
        migrations.CreateModel(
            name='TbNparentesco',
            fields=[
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_parentesco', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_parentesco', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion_parentesco', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_nparentesco',
            },
        ),
        migrations.CreateModel(
            name='TbNresponsabilidad',
            fields=[
                ('id_responsabilidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_responsabilidad', models.CharField(max_length=255)),
                ('fecha_registro_responsabilidad', models.DateTimeField()),
                ('descripcion_responsabilidad', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_nresponsabilidad',
            },
        ),
        migrations.CreateModel(
            name='TbNsexo',
            fields=[
                ('id_sexo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sexo', models.CharField(max_length=255)),
                ('fecha_registro_sexo', models.DateTimeField()),
                ('descripcion_sexo', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_nsexo',
            },
        ),
        migrations.CreateModel(
            name='TbNtipoCurso',
            fields=[
                ('id_tipo_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_curso', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ntipo_curso',
            },
        ),
        migrations.CreateModel(
            name='TbNtipoEstructura',
            fields=[
                ('id_tipo_estructura', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tipo_estructura_padre', models.IntegerField(blank=True, null=True)),
                ('nombre_tipo_estructura', models.CharField(max_length=255)),
                ('fecha_registro_tipo_estructura', models.DateTimeField()),
                ('descripcion_tipo_estructura', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_ntipo_estructura',
            },
        ),
        migrations.CreateModel(
            name='TbTempIdPersonaTarjeta',
            fields=[
                ('id_temp', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_temp_id_persona_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='TbRpersonaFamiliar',
            fields=[
                ('id_persona_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_familiar', models.ForeignKey(blank=True, db_column='id_familiar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_familiar_personaFamiliar', to='base.tbdpersona')),
                ('id_parentesco', models.ForeignKey(blank=True, db_column='id_parentesco', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnparentesco')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_persona_personaFamiliar', to='base.tbdpersona')),
            ],
            options={
                'db_table': 'tb_rpersona_familiar',
            },
        ),
        migrations.CreateModel(
            name='TbNprovincia',
            fields=[
                ('id_provincia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=255)),
                ('fecha_registro_provincia', models.DateTimeField()),
                ('descripcion_provincia', models.TextField(blank=True, null=True)),
                ('codigo_oficial_provincia', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
                ('abreviatura', models.CharField(blank=True, max_length=255, null=True)),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnpais')),
            ],
            options={
                'db_table': 'tb_nprovincia',
            },
        ),
        migrations.CreateModel(
            name='TbNmunicipio',
            fields=[
                ('id_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=255)),
                ('fecha_registro_municipio', models.DateTimeField()),
                ('descripcion_municipio', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('codigo_oficial_municipio', models.IntegerField(blank=True, null=True)),
                ('id_provincia', models.ForeignKey(blank=True, db_column='id_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnprovincia')),
            ],
            options={
                'db_table': 'tb_nmunicipio',
            },
        ),
        migrations.CreateModel(
            name='TbNestructura',
            fields=[
                ('id_estructura', models.IntegerField(primary_key=True, serialize=False)),
                ('id_estructura_padre', models.IntegerField(blank=True, null=True)),
                ('nombre_estructura', models.CharField(max_length=255)),
                ('codigo_externo', models.CharField(max_length=255)),
                ('codigo_area', models.CharField(max_length=255)),
                ('estructura_consejo', models.BooleanField(blank=True, null=True)),
                ('estructura_credencial', models.BooleanField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_tipo_estructura', models.ForeignKey(blank=True, db_column='id_tipo_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbntipoestructura')),
            ],
            options={
                'db_table': 'tb_nestructura',
            },
        ),
        migrations.CreateModel(
            name='TbNapto',
            fields=[
                ('id_apto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apto', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_apto', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_edificio', models.ForeignKey(blank=True, db_column='id_edificio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnedificio')),
            ],
            options={
                'db_table': 'tb_napto',
            },
        ),
        migrations.CreateModel(
            name='TbDpersonaTorpedo',
            fields=[
                ('tbuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_persona_torpedo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('ci', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_usuario_registro', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('id_municipio', models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnmunicipio')),
                ('id_pais', models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnpais')),
                ('id_provincia', models.ForeignKey(blank=True, db_column='id_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnprovincia')),
                ('id_sexo', models.ForeignKey(blank=True, db_column='id_sexo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnsexo')),
            ],
            options={
                'db_table': 'tb_dpersona_torpedo',
            },
            bases=('adminschema.tbuser',),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_apto',
            field=models.ForeignKey(blank=True, db_column='id_apto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnapto'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_carrera',
            field=models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncarrera'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoria'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_categoria_cientifica',
            field=models.ForeignKey(blank=True, db_column='id_categoria_cientifica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriacientifica'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_categoria_docente',
            field=models.ForeignKey(blank=True, db_column='id_categoria_docente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriadocente'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_categoria_residente',
            field=models.ForeignKey(blank=True, db_column='id_categoria_residente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriaresidente'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_edificio',
            field=models.ForeignKey(blank=True, db_column='id_edificio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnedificio'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_estructura',
            field=models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_estructura_persona', to='base.tbnestructura'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_estructura_consejo',
            field=models.ForeignKey(blank=True, db_column='id_estructura_consejo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_estructura_consejo_persona', to='base.tbnestructura'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_estructura_credencial',
            field=models.ForeignKey(blank=True, db_column='id_estructura_credencial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_estructura_credencial_persona', to='base.tbnestructura'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_grupo',
            field=models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbngrupo'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_municipio',
            field=models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnmunicipio'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_origen',
            field=models.ForeignKey(blank=True, db_column='id_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnorigen'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_pais',
            field=models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnpais'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_responsabilidad',
            field=models.ForeignKey(blank=True, db_column='id_responsabilidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnresponsabilidad'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_sexo',
            field=models.ForeignKey(blank=True, db_column='id_sexo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnsexo'),
        ),
        migrations.AddField(
            model_name='tbdpersona',
            name='id_tipo_curso',
            field=models.ForeignKey(blank=True, db_column='id_tipo_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbntipocurso'),
        ),
    ]
