# Generated by Django 4.2.5 on 2023-10-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbNcarrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_carrera', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ncarrera',
            },
        ),
        migrations.CreateModel(
            name='TbNcategoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('fecha_registro_categoria', models.DateTimeField()),
                ('descripcion_categoria', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_ncategoria',
            },
        ),
        migrations.CreateModel(
            name='TbNcategoriaCientifica',
            fields=[
                ('id_categoria_cientifica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_cientifica', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ncategoria_cientifica',
            },
        ),
        migrations.CreateModel(
            name='TbNcategoriaDocente',
            fields=[
                ('id_categoria_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_docente', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ncategoria_docente',
            },
        ),
        migrations.CreateModel(
            name='TbNcategoriaResidente',
            fields=[
                ('id_categoria_residente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_residente', models.TextField()),
                ('fecha_registro', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('siglas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ncategoria_residente',
            },
        ),
        migrations.CreateModel(
            name='TbNedificio',
            fields=[
                ('id_edificio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_edificio', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_edificio', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_nedificio',
            },
        ),
        migrations.CreateModel(
            name='TbNgrupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ngrupo',
            },
        ),
        migrations.CreateModel(
            name='TbNorigen',
            fields=[
                ('id_origen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_origen', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_origen', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_norigen',
            },
        ),
        migrations.CreateModel(
            name='TbNpais',
            fields=[
                ('nombre_pais', models.CharField(max_length=255)),
                ('fecha_registro_pais', models.DateTimeField()),
                ('descripcion_pais', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'tb_npais',
            },
        ),
        migrations.CreateModel(
            name='TbNparentesco',
            fields=[
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parentesco', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion_parentesco', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_nparentesco',
            },
        ),
        migrations.CreateModel(
            name='TbNresponsabilidad',
            fields=[
                ('id_responsabilidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_responsabilidad', models.CharField(max_length=255)),
                ('fecha_registro_responsabilidad', models.DateTimeField()),
                ('descripcion_responsabilidad', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_nresponsabilidad',
            },
        ),
        migrations.CreateModel(
            name='TbNsexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sexo', models.CharField(max_length=255)),
                ('fecha_registro_sexo', models.DateTimeField()),
                ('descripcion_sexo', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_nsexo',
            },
        ),
        migrations.CreateModel(
            name='TbNtipoCurso',
            fields=[
                ('id_tipo_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_curso', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ntipo_curso',
            },
        ),
        migrations.CreateModel(
            name='TbNtipoEstructura',
            fields=[
                ('id_tipo_estructura', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_estructura_padre', models.IntegerField(blank=True, null=True)),
                ('nombre_tipo_estructura', models.CharField(max_length=255)),
                ('fecha_registro_tipo_estructura', models.DateTimeField()),
                ('descripcion_tipo_estructura', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tipo Estructura',
                'verbose_name_plural': 'Tipo Estructuras',
                'db_table': 'tb_ntipo_estructura',
            },
        ),
        migrations.CreateModel(
            name='TbTempIdPersonaTarjeta',
            fields=[
                ('id_temp', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_temp_id_persona_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='TbRpersonaFamiliar',
            fields=[
                ('id_persona_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_parentesco', models.ForeignKey(blank=True, db_column='id_parentesco', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnparentesco')),
            ],
            options={
                'db_table': 'tb_rpersona_familiar',
            },
        ),
        migrations.CreateModel(
            name='TbNprovincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=255)),
                ('fecha_registro_provincia', models.DateTimeField()),
                ('descripcion_provincia', models.TextField(blank=True, null=True)),
                ('codigo_oficial_provincia', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
                ('abreviatura', models.CharField(blank=True, max_length=255, null=True)),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnpais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'tb_nprovincia',
            },
        ),
        migrations.CreateModel(
            name='TbNmunicipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=255)),
                ('fecha_registro_municipio', models.DateTimeField()),
                ('descripcion_municipio', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('codigo_oficial_municipio', models.IntegerField(blank=True, null=True)),
                ('id_provincia', models.ForeignKey(blank=True, db_column='id_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnprovincia')),
            ],
            options={
                'db_table': 'tb_nmunicipio',
            },
        ),
        migrations.CreateModel(
            name='TbNestructura',
            fields=[
                ('id_estructura', models.AutoField(primary_key=True, serialize=False)),
                ('id_estructura_padre', models.IntegerField(blank=True, null=True)),
                ('nombre_estructura', models.CharField(max_length=255)),
                ('codigo_externo', models.CharField(max_length=255)),
                ('codigo_area', models.CharField(max_length=255)),
                ('estructura_consejo', models.BooleanField(blank=True, null=True)),
                ('estructura_credencial', models.BooleanField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_tipo_estructura', models.ForeignKey(blank=True, db_column='id_tipo_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbntipoestructura')),
            ],
            options={
                'db_table': 'tb_nestructura',
            },
        ),
        migrations.CreateModel(
            name='TbNapto',
            fields=[
                ('id_apto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apto', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descripcion_apto', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_edificio', models.ForeignKey(blank=True, db_column='id_edificio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnedificio')),
            ],
            options={
                'db_table': 'tb_napto',
            },
        ),
    ]
