# Generated by Django 4.2.5 on 2023-10-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_persona_id_provincia'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbnapto',
            options={'verbose_name': 'Apartamento', 'verbose_name_plural': 'Apartamentos'},
        ),
        migrations.AlterModelOptions(
            name='tbncarrera',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='tbncategoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='tbncategoriacientifica',
            options={'verbose_name': 'Categorias Cientifica', 'verbose_name_plural': 'Categorias Cientificas'},
        ),
        migrations.AlterModelOptions(
            name='tbncategoriadocente',
            options={'verbose_name': 'Categorias Docente', 'verbose_name_plural': 'Categorias Docentes'},
        ),
        migrations.AlterModelOptions(
            name='tbncategoriaresidente',
            options={'verbose_name': 'Categorias Residente', 'verbose_name_plural': 'Categorias Residentes'},
        ),
        migrations.AlterModelOptions(
            name='tbnedificio',
            options={'verbose_name': 'Edificio', 'verbose_name_plural': 'Edificios'},
        ),
        migrations.AlterModelOptions(
            name='tbnestructura',
            options={'verbose_name': 'Estructura', 'verbose_name_plural': 'Estructuras'},
        ),
        migrations.AlterModelOptions(
            name='tbngrupo',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='tbnmunicipio',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='tbnorigen',
            options={'verbose_name': 'Origen', 'verbose_name_plural': 'Origenes'},
        ),
        migrations.AlterModelOptions(
            name='tbnparentesco',
            options={'verbose_name': 'Parentesco', 'verbose_name_plural': 'Parentescos'},
        ),
        migrations.AlterModelOptions(
            name='tbnresponsabilidad',
            options={'verbose_name': 'Responsabilidad', 'verbose_name_plural': 'Responsabilidades'},
        ),
        migrations.AlterModelOptions(
            name='tbnsexo',
            options={'verbose_name': 'Sexo', 'verbose_name_plural': 'Sexos'},
        ),
        migrations.AlterModelOptions(
            name='tbntipocurso',
            options={'verbose_name': 'Tipo de curso', 'verbose_name_plural': 'Tipo de cursos'},
        ),
        migrations.RemoveField(
            model_name='tbnestructura',
            name='id_estructura_padre',
        ),
        migrations.RemoveField(
            model_name='tbntipoestructura',
            name='id_tipo_estructura_padre',
        ),
        migrations.AddField(
            model_name='tbnestructura',
            name='id_institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.institucion'),
        ),
        migrations.AddField(
            model_name='tbntipoestructura',
            name='id_institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.institucion'),
        ),
    ]
