# Generated by Django 4.2.5 on 2023-09-29 23:02

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('ci', models.CharField(max_length=255)),
                ('solapin', models.CharField(blank=True, max_length=255, null=True)),
                ('id_expediente', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField()),
                ('id_persona_foto', models.CharField(blank=True, max_length=36, null=True)),
                ('nombre_responsabilidad', models.TextField(blank=True, null=True)),
                ('codigo_solapin', models.CharField(blank=True, max_length=1, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_apto', models.ForeignKey(blank=True, db_column='id_apto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnapto')),
                ('id_carrera', models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncarrera')),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoria')),
                ('id_categoria_cientifica', models.ForeignKey(blank=True, db_column='id_categoria_cientifica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriacientifica')),
                ('id_categoria_docente', models.ForeignKey(blank=True, db_column='id_categoria_docente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriadocente')),
                ('id_categoria_residente', models.ForeignKey(blank=True, db_column='id_categoria_residente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriaresidente')),
                ('id_edificio', models.ForeignKey(blank=True, db_column='id_edificio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnedificio')),
                ('id_estructura', models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_estructura_persona', to='base.tbnestructura')),
                ('id_estructura_consejo', models.ForeignKey(blank=True, db_column='id_estructura_consejo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_estructura_consejo_persona', to='base.tbnestructura')),
                ('id_estructura_credencial', models.ForeignKey(blank=True, db_column='id_estructura_credencial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_estructura_credencial_persona', to='base.tbnestructura')),
                ('id_grupo', models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbngrupo')),
                ('id_municipio', models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnmunicipio')),
                ('id_origen', models.ForeignKey(blank=True, db_column='id_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnorigen')),
                ('id_pais', models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnpais')),
                ('id_responsabilidad', models.ForeignKey(blank=True, db_column='id_responsabilidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnresponsabilidad')),
                ('id_sexo', models.ForeignKey(blank=True, db_column='id_sexo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnsexo')),
                ('id_tipo_curso', models.ForeignKey(blank=True, db_column='id_tipo_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbntipocurso')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('active_modules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('abastecimiento', 'Abastecimiento'), ('cajero', 'Cajero'), ('distribucion', 'Distribucion'), ('reservacion', 'Reservacion'), ('facturacion', 'Facturacion'), ('configuracion', 'Configuracion')], max_length=200), blank=True, default=list, size=None)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.institucion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
