# Generated by Django 4.2.5 on 2023-10-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbdpersonatorpedo',
            options={'verbose_name': 'Torpedo', 'verbose_name_plural': 'Torpedos'},
        ),
        migrations.AlterModelTable(
            name='tbdpersonatorpedo',
            table=None,
        ),
    ]
