# Generated by Django 4.2.5 on 2023-10-15 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbdpersonatorpedo',
            name='id_municipio',
            field=models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnmunicipio'),
        ),
        migrations.AddField(
            model_name='tbdpersonatorpedo',
            name='id_pais',
            field=models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnpais'),
        ),
        migrations.AddField(
            model_name='tbdpersonatorpedo',
            name='id_provincia',
            field=models.ForeignKey(blank=True, db_column='id_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnprovincia'),
        ),
        migrations.AddField(
            model_name='tbdpersonatorpedo',
            name='id_sexo',
            field=models.ForeignKey(blank=True, db_column='id_sexo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnsexo'),
        ),
        migrations.AddField(
            model_name='tbdconfiguracionpersona',
            name='id_institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.institucion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_apto',
            field=models.ForeignKey(blank=True, db_column='id_apto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnapto'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_carrera',
            field=models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncarrera'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoria'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_categoria_cientifica',
            field=models.ForeignKey(blank=True, db_column='id_categoria_cientifica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriacientifica'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_categoria_docente',
            field=models.ForeignKey(blank=True, db_column='id_categoria_docente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriadocente'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_categoria_residente',
            field=models.ForeignKey(blank=True, db_column='id_categoria_residente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriaresidente'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_configuracion_comensal',
            field=models.ForeignKey(blank=True, db_column='id_configuracion_comensal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacion.tbdconfiguracionpersona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_edificio',
            field=models.ForeignKey(blank=True, db_column='id_edificio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnedificio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_estructura',
            field=models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_estructura_persona', to='base.tbnestructura'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_grupo',
            field=models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbngrupo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_municipio',
            field=models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnmunicipio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_pais',
            field=models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnpais'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_provincia',
            field=models.ForeignKey(blank=True, db_column='id_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnprovincia'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_responsabilidad',
            field=models.ForeignKey(blank=True, db_column='id_responsabilidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnresponsabilidad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_sexo',
            field=models.ForeignKey(blank=True, db_column='id_sexo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnsexo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.institucion'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.institucion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.persona'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
