# Generated by Django 4.2.5 on 2023-09-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_remove_usuario_activo_alter_usuario_ci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='codigo_solapin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_apto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_carrera',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_categoria_cientifica',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_categoria_docente',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_categoria_residente',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_edificio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_estructura',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_estructura_consejo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_estructura_credencial',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_expediente',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_grupo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_municipio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_origen',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_pais',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_persona_foto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_responsabilidad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_sexo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_tipo_curso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_responsabilidad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='solapin',
        ),
    ]
