# Generated by Django 4.2.5 on 2023-09-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('autenticacion', '0003_remove_usuario_ci_remove_usuario_codigo_solapin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_solapin',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_apto',
            field=models.ForeignKey(blank=True, db_column='id_apto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnapto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_carrera',
            field=models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncarrera'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoria'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_categoria_cientifica',
            field=models.ForeignKey(blank=True, db_column='id_categoria_cientifica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriacientifica'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_categoria_docente',
            field=models.ForeignKey(blank=True, db_column='id_categoria_docente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriadocente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_categoria_residente',
            field=models.ForeignKey(blank=True, db_column='id_categoria_residente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbncategoriaresidente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_edificio',
            field=models.ForeignKey(blank=True, db_column='id_edificio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnedificio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_estructura',
            field=models.ForeignKey(blank=True, db_column='id_estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_estructura_persona', to='base.tbnestructura'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_estructura_consejo',
            field=models.ForeignKey(blank=True, db_column='id_estructura_consejo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_estructura_consejo_persona', to='base.tbnestructura'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_estructura_credencial',
            field=models.ForeignKey(blank=True, db_column='id_estructura_credencial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_estructura_credencial_persona', to='base.tbnestructura'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_expediente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_grupo',
            field=models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbngrupo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_municipio',
            field=models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnmunicipio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_origen',
            field=models.ForeignKey(blank=True, db_column='id_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnorigen'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_pais',
            field=models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnpais'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_persona_foto',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_responsabilidad',
            field=models.ForeignKey(blank=True, db_column='id_responsabilidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnresponsabilidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_sexo',
            field=models.ForeignKey(blank=True, db_column='id_sexo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbnsexo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_tipo_curso',
            field=models.ForeignKey(blank=True, db_column='id_tipo_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tbntipocurso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_responsabilidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='solapin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
